### ISSUE TITLE
Will not install with nodejs v18 or v20

### ISSUE THREAD

**Issue by manbunmelvin** [ncd-io/ncd-red-wireless#27]
I am having the same issue as the person before me, I have no idea what could be wrong but I have tried v18 and v 20 and the ncd-red-wireless will not install. Node red dashboard will install but no matter what I try this code wont download. Did anyone solve the other persons problem?  I have a sensor coming in a week or so and need to use ncd wireless code for my application

**Comment by manbunmelvin** [comment]
This is my log from when I try to install it.
2023-10-06T20:22:35.206Z npm.cmd install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict ncd-red-wireless@1.6.22
2023-10-06T20:22:35.985Z [err] npm
2023-10-06T20:22:35.986Z [err]  
2023-10-06T20:22:35.986Z [err] WARN config production Use `--omit=dev` instead.
2023-10-06T20:22:47.458Z [err] npm
2023-10-06T20:22:47.459Z [err]  WARN cleanup Failed to remove some directories [
2023-10-06T20:22:47.459Z [err] npm WARN cleanup   [
2023-10-06T20:22:47.459Z [err] npm WARN cleanup     'C:\\Users\\jacobc02\\.node-red\\node_modules\\i2c-bus',
2023-10-06T20:22:47.459Z [err] npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\jacobc02\.node-red\node_modules\i2c-bus'] {
2023-10-06T20:22:47.459Z [err] npm
2023-10-06T20:22:47.459Z [err]  WARN cleanup       errno: -4082,
2023-10-06T20:22:47.459Z [err] npm WARN cleanup       code: 'EBUSY',
2023-10-06T20:22:47.459Z [err] npm WARN cleanup       syscall: 'rmdir',
2023-10-06T20:22:47.459Z [err] npm WARN 
2023-10-06T20:22:47.459Z [err] cleanup       path: 'C:\\Users\\jacobc02\\.node-red\\node_modules\\i2c-bus'
2023-10-06T20:22:47.459Z [err] npm WARN cleanup     }
2023-10-06T20:22:47.459Z [err] npm WARN cleanup   ],
2023-10-06T20:22:47.459Z [err] npm WARN cleanup   [
2023-10-06T20:22:47.459Z [err] npm WARN cleanup     'C:\\Users\\jacobc02\\.node-red\\node_modules\\i2c-bus',
2023-10-06T20:22:47.459Z [err] npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\jacobc02\.node-red\node_modules\i2c-bus'] {
2023-10-06T20:22:47.459Z [err] npm
2023-10-06T20:22:47.459Z [err]  WARN cleanup       errno: -4082,
2023-10-06T20:22:47.459Z [err] npm WARN cleanup       code: 'EBUSY',
2023-10-06T20:22:47.459Z [err] npm WARN cleanup
2023-10-06T20:22:47.459Z [err]        syscall: 'rmdir',
2023-10-06T20:22:47.459Z [err] npm
2023-10-06T20:22:47.459Z [err]  WARN cleanup       path: 'C:\\Users\\jacobc02\\.node-red\\node_modules\\i2c-bus'
2023-10-06T20:22:47.459Z [err] npm
2023-10-06T20:22:47.459Z [err]  WARN cleanup
2023-10-06T20:22:47.459Z [err]      }
2023-10-06T20:22:47.459Z [err] npm
2023-10-06T20:22:47.459Z [err]  WARN cleanup   ]
2023-10-06T20:22:47.459Z [err] npm
2023-10-06T20:22:47.459Z [err]  WARN cleanup ]
2023-10-06T20:22:47.651Z [err] npm ERR!
2023-10-06T20:22:47.651Z [err]  code 1
2023-10-06T20:22:47.651Z [err] npm ERR! path C:\Users\jacobc02\.node-red\node_modules\@serialport\bindings
2023-10-06T20:22:47.653Z [err] npm ERR! command failed
2023-10-06T20:22:47.653Z [err] npm ERR! command C:\windows\system32\cmd.exe /d /s /c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2023-10-06T20:22:47.653Z [err] npm ERR! gyp info it worked if it ends with ok
2023-10-06T20:22:47.653Z [err] npm ERR! gyp info using node-gyp@9.4.0
2023-10-06T20:22:47.653Z [err] npm ERR!
2023-10-06T20:22:47.653Z [err]  gyp info using node@20.8.0 | win32 | x64
2023-10-06T20:22:47.653Z [err] npm ERR! gyp info find Python using Python version 3.12.0 found at "C:\Python312\python.exe"
2023-10-06T20:22:47.653Z [err] npm ERR! gyp info find VS using VS2022 (17.7.34031.279) found at:
2023-10-06T20:22:47.653Z [err] npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
2023-10-06T20:22:47.653Z [err] npm ERR!
2023-10-06T20:22:47.653Z [err]  gyp info find VS run with --verbose for detailed information
2023-10-06T20:22:47.653Z [err] npm ERR! gyp info spawn C:\Python312\python.exe
2023-10-06T20:22:47.653Z [err] npm ERR! gyp info spawn args [
2023-10-06T20:22:47.653Z [err] npm ERR! gyp info spawn args   'C:\\Users\\jacobc02\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
2023-10-06T20:22:47.653Z [err] npm ERR!
2023-10-06T20:22:47.653Z [err]  gyp info spawn args   'binding.gyp',
2023-10-06T20:22:47.653Z [err] npm ERR! gyp info spawn args   '-f',
2023-10-06T20:22:47.653Z [err] npm ERR! gyp info spawn args   'msvs',
2023-10-06T20:22:47.653Z [err] npm ERR!
2023-10-06T20:22:47.653Z [err]  gyp info spawn args   '-I',
2023-10-06T20:22:47.653Z [err] npm ERR! gyp info spawn args   'C:\\Users\\jacobc02\\.node-red\\node_modules\\@serialport\\bindings\\build\\config.gypi',
2023-10-06T20:22:47.653Z [err] npm
2023-10-06T20:22:47.653Z [err]  ERR! gyp info spawn args   '-I',
2023-10-06T20:22:47.653Z [err] npm ERR!
2023-10-06T20:22:47.653Z [err]  gyp info spawn args   'C:\\Users\\jacobc02\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
2023-10-06T20:22:47.653Z [err] npm ERR!
2023-10-06T20:22:47.653Z [err]  gyp info spawn args   '-I',
2023-10-06T20:22:47.653Z [err] npm ERR!
2023-10-06T20:22:47.653Z [err]  gyp info spawn args   'C:\\Users\\jacobc02\\AppData\\Local\\node-gyp\\Cache\\20.8.0\\include\\node\\common.gypi',
2023-10-06T20:22:47.653Z [err] npm ERR!
2023-10-06T20:22:47.653Z [err]  gyp info spawn args   '-Dlibrary=shared_library',
2023-10-06T20:22:47.653Z [err] npm ERR!
2023-10-06T20:22:47.653Z [err]  gyp info spawn args   '-Dvisibility=default',
2023-10-06T20:22:47.653Z [err] npm ERR!
2023-10-06T20:22:47.653Z [err]  gyp info spawn args   '-Dnode_root_dir=C:\\Users\\jacobc02\\AppData\\Local\\node-gyp\\Cache\\20.8.0',
2023-10-06T20:22:47.653Z [err] npm 
2023-10-06T20:22:47.653Z [err] ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\jacobc02\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
2023-10-06T20:22:47.653Z [err] npm ERR!
2023-10-06T20:22:47.653Z [err]  gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\jacobc02\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.8.0\\\\<(target_arch)\\\\node.lib',
2023-10-06T20:22:47.653Z [err] npm ERR!
2023-10-06T20:22:47.653Z [err]  gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\jacobc02\\.node-red\\node_modules\\@serialport\\bindings',
2023-10-06T20:22:47.653Z [err] npm ERR!
2023-10-06T20:22:47.653Z [err]  gyp info spawn args   '-Dnode_engine=v8',
2023-10-06T20:22:47.653Z [err] npm ERR! gyp info spawn args   '--depth=.',
2023-10-06T20:22:47.654Z [err] npm ERR! gyp info spawn args   '--no-parallel',
2023-10-06T20:22:47.654Z [err] npm ERR! gyp info spawn args   '--generator-output',
2023-10-06T20:22:47.654Z [err] npm ERR! gyp info spawn args   'C:\\Users\\jacobc02\\.node-red\\node_modules\\@serialport\\bindings\\build',
2023-10-06T20:22:47.654Z [err] npm ERR! gyp info spawn args   '-Goutput_dir=.'
2023-10-06T20:22:47.654Z [err] npm
2023-10-06T20:22:47.654Z [err]  ERR! gyp info spawn args ]
2023-10-06T20:22:47.654Z [err] npm
2023-10-06T20:22:47.654Z [err]  ERR! Traceback (most recent call last):
2023-10-06T20:22:47.654Z [err] npm ERR!
2023-10-06T20:22:47.654Z [err]    File "C:\Users\jacobc02\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
2023-10-06T20:22:47.654Z [err] npm ERR!     import gyp  # noqa: E402
2023-10-06T20:22:47.654Z [err] npm ERR!     ^^^^^^^^^^
2023-10-06T20:22:47.654Z [err] npm
2023-10-06T20:22:47.654Z [err]  ERR!   File "C:\Users\jacobc02\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
2023-10-06T20:22:47.654Z [err] npm 
2023-10-06T20:22:47.654Z [err] ERR!     import gyp.input
2023-10-06T20:22:47.654Z [err] npm ERR!
2023-10-06T20:22:47.654Z [err]    File "C:\Users\jacobc02\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
2023-10-06T20:22:47.654Z [err] npm ERR!     from distutils.version import StrictVersion
2023-10-06T20:22:47.654Z [err] npm ERR! ModuleNotFoundError: No module named 'distutils'
2023-10-06T20:22:47.654Z [err] npm 
2023-10-06T20:22:47.654Z [err] ERR! gyp ERR! configure error 
2023-10-06T20:22:47.654Z [err] npm ERR!
2023-10-06T20:22:47.654Z [err]  gyp ERR! stack Error: `gyp` failed with exit code: 1
2023-10-06T20:22:47.654Z [err] npm ERR!
2023-10-06T20:22:47.654Z [err]  gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\jacobc02\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:325:16)
2023-10-06T20:22:47.654Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
2023-10-06T20:22:47.654Z [err] npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
2023-10-06T20:22:47.654Z [err] npm ERR! gyp ERR! System Windows_NT 10.0.19045
2023-10-06T20:22:47.654Z [err] npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jacobc02\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
2023-10-06T20:22:47.654Z [err] npm ERR!
2023-10-06T20:22:47.654Z [err]  gyp ERR! cwd C:\Users\jacobc02\.node-red\node_modules\@serialport\bindings
2023-10-06T20:22:47.654Z [err] npm ERR! gyp ERR! node -v v20.8.0
2023-10-06T20:22:47.654Z [err] npm
2023-10-06T20:22:47.654Z [err]  ERR! gyp ERR! node-gyp -v v9.4.0
2023-10-06T20:22:47.654Z [err] npm 
2023-10-06T20:22:47.654Z [err] ERR! gyp ERR! not ok
2023-10-06T20:22:47.657Z [err] 
2023-10-06T20:22:47.657Z [err] npm ERR! A complete log of this run can be found in: C:\Users\jacobc02\AppData\Local\npm-cache\_logs\2023-10-06T20_22_35_929Z-debug-0.log
2023-10-06T20:22:47.682Z rc=1
